### PR TITLE
refactor: settings responsive

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://github.com/ArkEcosystem/payvo-wallet/issues/1066

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Opening this menu in dark mode is interesting :D 

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
On breakpoint 375, these settings should be stacked rather than side by side.

Design
image


Implementation
image

I've also just noticed that this PR is labelled as WIP but it's also open, so if you've not finished yet then no worries.

**Comment by alfonsobries** [comment]
My bad @samharperpittam, this PR is a WIP I forget to mark it as draft 🤦🏻‍♂️. sorry about that

**Comment by alfonsobries** [comment]
@samharperpittam this is ready now

Notice that we don't have a design for the dark menu so I came up with this:
image (waiting for confirmation from Oleg)

I updated the settings internal pages to be responsive, which should work fine but some pages are a little different from the design, they may have different buttons or form fields, I am not fixing that in this PR.

**Pull request merged**
