### PR TITLE
refactor: contacts responsiveness

### LINKED ISSUE #1008: [Contacts] implement responsive designs
### Describe the refactor you'd like to request

https://www.figma.com/file/o6b1tEMOdUtHv7ijVs6pMX/Payvo-DW?node-id=5183%3A171701

The responsive designs of the `Contacts` screen need to be implemented.

### PR DESCRIPTION
**Pull request by alesmit**
## Summary

Closes #1008

## Checklist

- [x] My changes look good in both light AND dark mode
- [x] The change is not hardcoded to a single network, but has multi-asset in mind
- [x] I checked my changes for obvious issues, debug statements and commented code
- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Using a long contact name can cause the the content of the page to exceed the allowed width on 1024 and lower. Truncation of the name is required:

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Not exactly sure what's going on here, but the 'Qredit' green send butto be an identical colour to the others:
image

**Comment by dated** [comment]
> Using a long contact name can cause the the content of the page to exceed the allowed width on 1024 and lower. Truncation of the name and/or addresses is required:

should be fixed now

**Comment by dated** [comment]
> Not exactly sure what's going on here, but the 'Qredit' green send button should be identical colour to the others: image

there is https://github.com/ArkEcosystem/payvo-wallet/issues/1112 that will take care of the disabled styles once they are available.

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@dated - Still seeing issues with the name length. Can you also check please?

image

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
