### PR TITLE
refactor: implement responsive designs in wallet creation flow

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Closes https://github.com/ArkEcosystem/payvo-wallet/issues/1004

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@goga-m  - On the 'Your Passphrase' page on breakpoint 640, the passphrase words should be in rows of 4 as per the design. Within this PR they are in rows of 2. 

**Design**
image


**Implementation**
image

**Comment by goga-m** [comment]
@samharperpittam fixed :white_check_mark:

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Final comment on this PR

On the Your Passphrase page on 375, the grey background within the 'Copy or Download Mnemonic' section should be full width 

**Design**
image

**Comment by goga-m** [comment]
Missed that one @samharperpittam :hide:
Should be fixed now :+1:

**Review by samharperpittam — APPROVED** [review]

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
