### PR TITLE
refactor: currency dropdown issues & improvements

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://github.com/ArkEcosystem/payvo-wallet/issues/1016

- Refactors the dropdown to use tippy which helps to avoid the max-width issues that cause the issue described on the ticket
- As plus it helps to dynamically position the dropdown (with the original position as default) when there is not enough space which I think is a nice addition that will solve a lot of issues related to the limitations of CSS-only dropdowns, it's going to work better on mobile and is going to prevent other issues (for example the white space in the last screenshot below)
- In general, improves the dropdown functionality by using a dynamic position powered by tippy (see videos as an example)

Note: This PR affects all the dropdowns. I tried to make comprehensive tests in all the dropdowns I was able to find but I recommend that whoever reviews this PR double-check (the updated snapshots can be used as references to know which components depends on the dropdown)

https://user-images.githubusercontent.com/17262776/153934646-094dc68b-1852-4d1b-8186-747d74f0911f.mov

https://user-images.githubusercontent.com/17262776/153934947-4c3a6f77-9317-49b1-a9a3-97c2a37a892b.mov

Screen Shot 2022-02-14 at 12 44 07

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by alfonsobries** [comment]
In draft because still dealing with the tests

**Comment by alfonsobries** [comment]
Hey @goga-m @faustbrian, this is the second whole day I spent trying to fix the tests here (I know, I should have sought help sooner, but passed the whole day with the sensation that I was about to fix it)

As you can see in the [vercel deployment](https://payvo-wallet-27esvmawy-arkecosystem.vercel.app/) the dropdowns are working fine, but some tests are broken. There are different errors but the main one is that the test takes a lot of time, so it throws a timeout error (as far as I can tell is related to Tippy re-rendering the dropdown content)

As you can see in the PR history I tried a lot of alternatives without luck.

The issue is pretty silly, it may be tricky but should be possible to fix the error using the current CSS-only dropdown, but I wanted to go forward and use a dynamic dropdown, which generally improves the UX and prevents a lot of issues as I explained in the description of this PR. I did not anticipate that it would cause so many issues.

So...
- Let you know because maybe one of you want to take a look, maybe you find a way to fix the tests or optimize the component
- Or, I'm considering closing this PR and starting again with a CSS-only solution. I think it would be a shame, but perhaps considering the priorities, it is best to avoid wasting more time for the moment so I can focus on other issues.

Let me know what do you think

**Comment by alfonsobries** [comment]
@goga-m @faustbrian update:

[Increased the testTimeout](https://github.com/ArkEcosystem/payvo-wallet/pull/1039/commits/31d0ff0f1b059c247faee4c45fe22d9d5da8f02a), and that did the trick. Not sure if the best solution, though. What do you think?  (The domains-exchange tests need even more time)

**Comment by alfonsobries** [comment]
@goga-m @faustbrian did my best to optimize the dropdown but to fix the tests still needed to increase the testTimeout manually with `jest.setTimeout(20_000);. I see that you did the same for other tests so shouldn't be that bad

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
