### PR TITLE
refactor: implement responsive dropdown menus

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Closes https://github.com/ArkEcosystem/payvo-wallet/issues/1014

Adjusts responsiveness, alignment and sizes of the various dropdown menus (navigation menus, notifications dropdown, wallet filters, vote filters).

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by samharperpittam** [comment]
@goga-m  - The profile dropdown on 375 appears to be missing the "Balance" at the top of the menu. Is this something that you was planning on doing in a separate PR? 
image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
Also notifications seem to be a little wonky :D 

image

**Comment by goga-m** [comment]
@samharperpittam yes, this PR handles the sizes and the orientation of the dropdowns, the inner content adjustments will be handled in separate PRs. The notifications dropdown will be handled in https://github.com/ArkEcosystem/payvo-wallet/issues/1093 and just created https://github.com/ArkEcosystem/payvo-wallet/issues/1139 for the user menu

**Comment by samharperpittam** [comment]
> @samharperpittam yes, this PR handles the sizes and the orientation of the dropdown wrappers, the inner content adjustments will be handled in separate PRs. The notifications dropdown will be handled in #1093 and just created #1139 for the user menu

Okay thanks @goga-m - In which case things look good

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
